using Academy.Domain.Abstractions.Services.Main;

namespace Academy.Application.Services.Main;

public class LocalizationService : ILocalizationService
{
    private readonly Dictionary<string, Dictionary<string, string>> _messages = new()
    {
        ["en"] = new Dictionary<string, string>
        {
            ["DepartmentAlreadyExists"] = "Department with this name already exists",
            ["DepartmentHasTeachers"] = "Department has these teachers",
            ["TeacherAlreadyInDepartment"] = "Teacher is already in this department",
            ["TeacherAlreadyAssigned"] = "Teacher is already assigned to another department",
            ["TeacherNotAssigned"] = "Teacher is not assigned to this department",
            ["TeacherHasTeachers"] = "Teacher has these teachers",
            ["TeacherNotInSourceDepartment"] = "Teacher is not in the source department",
            ["PaginationError"] = "Page number and size must be positive numbers",
            ["DepartmentNotFound"] = "Department not found",
            ["DepartmentNameDescriptionHeadLength"] = "Department name and description head cannot exceed characters",
            ["NoDepartmentsFound"] = "No departments found",
            ["FacultyAlreadyExists"] = "Faculty with this name already exists",
            ["FacultyHasDepartments"] = "Cannot delete faculty with assigned departments",
            ["DepartmentAlreadyInFaculty"] = "Department is already in this faculty",
            ["DepartmentNotInFaculty"] = "Department is not in this faculty",
            ["FacultyNotFound"] = "Faculty with ID not found",
            ["NoFacultiesFound"] = "No faculties found",
            ["FacultyNameEmpty"] = "Faculty name cannot be empty",
            ["FacultyNameDescriptionDeanLength"] = "Faculty name and description head cannot exceed max characters",
            ["FacultyNameLength"] = "Faculty name cannot exceed max characters",
            ["FacultyDescriptionEmpty"] = "Faculty description cannot be empty",
            ["FacultyDescriptionLength"] = "Faculty description cannot exceed max characters",
            ["FacultyDeanEmpty"] = "Faculty dean cannot be empty",
            ["FacultyDeanLength"] = "Faculty dean name cannot exceed max characters",
            ["FacultyGroupsEmpty"] = "Faculty must have at least one group",
            ["DepartmentNameEmpty"] = "Department name cannot be empty",
            ["DepartmentNameLength"] = "Department name cannot exceed max characters",
            ["DepartmentDescriptionEmpty"] = "Department description cannot be empty",
            ["DepartmentDescriptionLength"] = "Department description cannot exceed max characters",
            ["DepartmentHeadEmpty"] = "Head name cannot be empty",
            ["DepartmentHeadLength"] = "Head name cannot exceed max characters",
            ["DepartmentTeachersEmpty"] = "A department must have at least one teacher",
            ["GroupNameEmpty"] = "Group name cannot be empty",
            ["GroupNameLength"] = "Group name cannot exceed max characters",
            ["GroupStudentsEmpty"] = "A group must have at least one student",
            ["GroupNotFound"] = "Group with ID not found",
            ["GroupNoGroups"] = "No groups found",
            ["GroupAlreadyExists"] = "Group with this name already exists",
            ["GroupAlreadyInFaculty"] = "Group is already in this faculty",
            ["GroupAlreadyAssignedToTeacher"] = "The group is already assigned to this teacher",
            ["GroupNotInFaculty"] = "Group is not in this faculty",
            ["RoleNameEmpty"] = "Role name cannot be empty",
            ["RoleNameLength"] = "Role name cannot exceed max characters",
            ["RoleDescriptionLength"] = "Role description cannot exceed max characters",
            ["RoleNameAndDescriptionLength"] = "Role name and description cannot exceed max characters",
            ["RoleNotFound"] = "Role not found",
            ["RoleNoRoles"] = "No roles found",
            ["RoleAlreadyExists"] = "Role with this name already exists",
            ["StudentFirstNameEmpty"] = "First name cannot be empty",
            ["StudentLastNameEmpty"] = "Last name cannot be empty",
            ["StudentFirstNameLength"] = "First name cannot exceed max characters",
            ["StudentLastNameLength"] = "Last name cannot exceed max characters",
            ["StudentNotFound"] = "Student with ID not found",
            ["StudentNoStudents"] = "No students found",
            ["StudentAlreadyExists"] = "Student with this name already exists",
            ["StudentAlreadyInGroup"] = "Student is already in this group",
            ["StudentNotInGroup"] = "Student is not in this group",
            ["StudentNotInSourceGroup"] = "Student is not in the source group",
            ["TeacherFirstNameEmpty"] = "First name cannot be empty",
            ["TeacherLastNameEmpty"] = "Last name cannot be empty",
            ["TeacherFirstNameLength"] = "First name cannot exceed max characters",
            ["TeacherLastNameLength"] = "Last name cannot exceed max characters",
            ["TeacherDepartmentIdEmpty"] = "DepartmentId cannot be empty",
            ["TeacherGroupsEmpty"] = "Teacher must have at least one group",
            ["TeacherNotFound"] = "Teacher with ID not found",
            ["TeacherNoTeachers"] = "No teachers found",
            ["TeacherAlreadyExists"] = "Teacher with this name already exists",
            ["UserUsernameEmpty"] = "Username cannot be empty",
            ["UserPasswordEmpty"] = "Password cannot be empty",
            ["UserEmailEmpty"] = "Email cannot be empty",
            ["UserPasswordFormatInvalid"] = "Invalid password format. The password must contain at least one letter, one digit, and one special character, and must be at least 8 characters long",
            ["UserEmailFormatInvalid"] = "Invalid email format",
            ["UserUsernameFormatInvalid"] = "Invalid username format",
            ["UserUsernameLength"] = "Username cannot exceed max characters",
            ["UserPasswordLength"] = "Password cannot exceed max characters",
            ["UserEmailLength"] = "Email cannot exceed max characters",
            ["UserRefreshTokenLength"] = "Refresh token cannot exceed max characters",
            ["UserNotFound"] = "User with ID not found",
            ["UserNoUsers"] = "No users found",
            ["UserAlreadyExists"] = "User with this credentials already exists",
            ["UserAlreadyInTargetRole"] = "User is already in this role",
            ["UserInvalidCredentials"] = "Invalid username or password",
            ["UserEmailInvalid"] = "Invalid email address",
            ["UserRoleEmpty"] = "Role cannot be null",
            ["UserRefreshTokenExpired"] = "Refresh token expiry time must be in the future",
            ["DepartmentEstablishedDateFuture"] = "Established date cannot be in the future",
            ["DepartmentFacultyIdEmpty"] = "FacultyId cannot be empty",
            ["GroupFacultyIdEmpty"] = "FacultyId cannot be empty",
            ["GroupTeacherIdEmpty"] = "TeacherId cannot be empty",
            ["DepartmentDescriptionFormatInvalid"] = "Invalid department description format",
            ["DepartmentNameFormatInvalid"] = "Invalid department name format",
            ["DepartmentHeadFormatInvalid"] = "Invalid department head format",
            ["InvalidPageParameters"] = "Page number and size must be positive numbers",
            ["EntityNotFound"] = "Entity with ID not found",
            ["NoEntitiesFound"] = "No entities found",
            ["InvalidId"] = "Invalid ID format",
            ["UnauthorizedAccess"] = "Unauthorized access",
            ["ForbiddenAccess"] = "Access forbidden",
            ["ValidationError"] = "Validation error occurred",
            ["ConcurrencyError"] = "The record was modified by another user",
            ["DatabaseError"] = "Database error occurred",
            ["TeacherInvalidDepartment"] = "Invalid department assignment for teacher",
            ["TeacherInvalidGroup"] = "Invalid group assignment for teacher",
            ["TeacherMaxGroupsReached"] = "Teacher has reached maximum number of groups",
            ["TeacherScheduleConflict"] = "Schedule conflict detected for teacher",
            ["StudentInvalidGroup"] = "Invalid group assignment for student",
            ["StudentMaxGroupsReached"] = "Student has reached maximum number of groups",
            ["StudentScheduleConflict"] = "Schedule conflict detected for student",
            ["StudentAlreadyGraduated"] = "Student has already graduated",
            ["GroupMaxCapacityReached"] = "Group has reached maximum capacity",
            ["GroupInvalidTeacher"] = "Invalid teacher assignment for group",
            ["GroupInvalidFaculty"] = "Invalid faculty assignment for group",
            ["GroupScheduleConflict"] = "Schedule conflict detected for group",
            ["FacultyMaxDepartments"] = "Faculty has reached maximum number of departments",
            ["FacultyMaxGroups"] = "Faculty has reached maximum number of groups",
            ["FacultyInvalidDean"] = "Invalid dean assignment for faculty",
            ["DepartmentMaxTeachers"] = "Department has reached maximum number of teachers",
            ["DepartmentInvalidFaculty"] = "Invalid faculty assignment for department",
            ["DepartmentInvalidHead"] = "Invalid head assignment for department",
            ["UserInvalidRole"] = "Invalid role assignment for user",
            ["UserNotInRole"] = "The User Is Not In The Role",
            ["UserPasswordMismatch"] = "Password confirmation does not match",
            ["UserTokenExpired"] = "User token has expired",
            ["UserAccountLocked"] = "User account is locked",
            ["UserAccountDisabled"] = "User account is disabled",
            ["RoleInvalidPermissions"] = "Invalid permissions for role",
            ["RoleNameFormatInvalid"] = "Invalid role name format",
            ["RoleSystemReserved"] = "Cannot modify system reserved role",
            ["RoleMaxUsers"] = "Role has reached maximum number of users",
            ["ValidationNameRequired"] = "Name is required",
            ["ValidationDescriptionRequired"] = "Description is required",
            ["ValidationEmailFormat"] = "Invalid email format",
            ["ValidationPhoneFormat"] = "Invalid phone number format",
            ["ValidationDateRange"] = "Date must be between max date",
            ["ValidationMinLength"] = "Minimum length is max characters",
            ["ValidationMaxLength"] = "Maximum length is max characters",
            ["ValidationNumericRange"] = "Value must be between max date",
            ["FileTooBig"] = "File size exceeds maximum limit",
            ["FileInvalidType"] = "Invalid file type",
            ["FileUploadFailed"] = "File upload failed",
            ["FileNotFound"] = "File not found",
            ["ApiRateLimitExceeded"] = "API rate limit exceeded",
            ["ApiInvalidRequest"] = "Invalid API request",
            ["ApiVersionMismatch"] = "API version mismatch",
            ["ApiServiceUnavailable"] = "Service temporarily unavailable",
            ["LoginEmailEmpty"] = "Email cannot be empty",
            ["LoginEmailInvalid"] = "Invalid email format",
            ["LoginPasswordEmpty"] = "Password cannot be empty",
            ["RegisterUsernameEmpty"] = "Username cannot be empty",
            ["RegisterUsernameLength"] = "Username must not exceed max characters",
            ["RegisterEmailEmpty"] = "Email cannot be empty",
            ["RegisterEmailInvalid"] = "Invalid email format",
            ["RegisterEmailLength"] = "Email must not exceed max characters",
            ["RegisterPasswordEmpty"] = "Password cannot be empty",
            ["RegisterPasswordMinLength"] = "Password must be at least 6 characters",
            ["RegisterConfirmPasswordEmpty"] = "Confirm password cannot be empty",
            ["RegisterPasswordsDoNotMatch"] = "Passwords do not match",
            ["InvalidCredentials"] = "Invalid email or password",
            ["EmailAlreadyExists"] = "Email already exists",
            ["InvalidOrExpiredRefreshToken"] = "Invalid or expired refresh token",
            ["InvalidRefreshToken"] = "Invalid refresh token",
            ["NoChangesMadeToRole"] = "No changes were made to the role",
            ["NoChangesMadeToGroup"] = "No changes were made to the group",
            ["NoChangesMadeToFaculty"] = "No changes were made to the faculty",
            ["NoChangesMadeToDepartment"] = "No changes were made to the department",
            ["NoChangesMadeToStudent"] = "No changes were made to the student",
            ["NoChangesMadeToTeacher"] = "No changes were made to the teacher",
            ["NoChangesMadeToUser"] = "No changes were made to the user",
            ["OldPasswordIncorrect"] = "Old password is incorrect",
            ["InvalidClientRequest"] = "Invalid client request",
            ["InvalidAccessToken"] = "Invalid access token",
            ["InvalidRefreshTokenOrTokenExpired"] = "Invalid refresh token or token expired",
        },
        ["ru"] = new Dictionary<string, string>
        {
            
        },
        ["az"] = new Dictionary<string, string>
        {
            
        }
    };

    public string GetMessage(string key, string language)
    {
        var lengthInfo = key.Split(':');
        var baseKey = lengthInfo[0]; 
        var length = lengthInfo.Length > 1 ? lengthInfo[1] : string.Empty;

        if (!_messages.ContainsKey(language))
            language = "en";

        var message = _messages[language].TryGetValue(baseKey, out var baseMessage)
            ? baseMessage
            : _messages["en"].TryGetValue(baseKey, out baseMessage)
                ? baseMessage
                : $"Message for key '{baseKey}' not found";

        return string.IsNullOrEmpty(length) ? message : $"{message}: {length}";
    }

}